# Monitor setup
# PC
# monitor=HDMI-A-2,2560x1080@100,0x0,1
# monitor=HDMI-A-1,1920x1080@75,2560x0,1


# monitor=HDMI-A-1,disabled

# Laptop
 monitor = eDP-1, 1920x1080@60, 0x0,1
# monitor=eDP-1,disabled
monitor = , preferred, auto, 1,
# monitor = , preferred, auto, 1, mirror, eDP-1

source=~/.config/hypr/exec.conf # Programs to exec on startup
source=~/.config/hypr/keybinds.conf # keybinds
source=~/.config/hypr/windowrules.conf # Window Rules
source=~/.config/hypr/plugins.conf

# env = QT_QPA_PLATFORM,wayland;xcb
# env = QT_QPA_PLATFORMTHEME,qt6ct

misc {
    background_color = rgb(000000)
    disable_hyprland_logo = true
    disable_splash_rendering = true
    vfr = true
}

input {
    follow_mouse=1
    kb_layout=pl
    numlock_by_default=yes
    kb_options = ctrl:nocaps # hhkb from wish.com
    touchpad {
        disable_while_typing=no
        natural_scroll=yes
        tap-and-drag=yes
    }
}
cursor {
    no_hardware_cursors = true
}
general {
	gaps_in = 3
	gaps_out = 3

	border_size = 9
	col.inactive_border = rgb(52263e)
	col.active_border = rgb(ac3231)
}

decoration {
	dim_inactive = true
	dim_strength = 0.4

	blur {
		size = 2
		passes = 4
	}

	shadow {
		enabled = false
		range = 18
		render_power = 3
		color = rgba(000000aa)
		offset = 2, 2
	}
}
dwindle {
    force_split = 2
    pseudotile = 1
    split_width_multiplier = 1.5 # make 21:9 monitors split the same as 16:9
}

animations {
    enabled = false
    bezier = easeOutQuint,0.23,1,0.32,1
    bezier = easeInOutCubic,0.65,0.05,0.36,1
    bezier = linear,0,0,1,1
    animation = global, 1, 2, default
    animation = border, 0
    animation = windows, 1, 2, easeOutQuint, slide
    animation = windowsIn, 1, 2, easeOutQuint, slide
    animation = windowsOut, 1, 2, easeOutQuint, slide
    animation = layers, 1, 2, easeOutQuint, slide
    animation = layersIn, 1, 2, easeOutQuint, slide
    animation = layersOut, 1, 2, linear, slide
    animation = fade, 1, 2, default
    animation = fadeIn, 1, 2, easeOutQuint
    animation = fadeOut, 1, 2, easeOutQuint
    animation = fadeLayersIn, 1, 4, easeOutQuint
    animation = fadeLayersOut, 1, 4, easeOutQuint
    animation = workspaces, 1, 3, easeInOutCubic, slide
    animation = workspacesIn, 1, 3, easeInOutCubic, slide
    animation = workspacesOut, 1, 3, easeInOutCubic, slide
}
